name: mutualfund_info
description: "Flutter Package to get the current(Today's) NAVs of Mutual Funds in India."
version: 0.0.3
homepage: https://www.kumarsundaram.com

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# Publisher Information
repository: https://github.com/sundaramkumar/mutualfund_info_flutter_package
issue_tracker: https://github.com/sundaramkumar/mutualfund_info_flutter_package/issues
maintainers:
  - "Kumar Sundaram <guyfromchennai@gmail.com>"

# License
license: MIT

# Topics
topics:
  - mutualfund
  - mf
  - mfindia
  - nav
